### ISSUE TITLE
Unable to compile | Invalid operands error

### ISSUE THREAD

**Issue by kalravibhor** [githubharald/DeslantImg#1]
Hi,

I am trying to compile the codebase as instructed by using `g++ --std=c++11 src/cpp/main.cpp src/cpp/DeslantImgCPU.cpp `pkg-config --cflags --libs opencv` -o DeslantImg`. However I run into the below mentioned error to which I am unable to find a solution.

`In file included from src/cpp/DeslantImgCPU.cpp:1:
In file included from src/cpp/DeslantImgCPU.hpp:2:
In file included from /usr/local/Cellar/opencv/3.3.0_3/include/opencv2/core.hpp:52:
In file included from /usr/local/Cellar/opencv/3.3.0_3/include/opencv2/core/cvdef.h:424:
In file included from /Library/Developer/CommandLineTools/usr/include/c++/v1/array:109:
/Library/Developer/CommandLineTools/usr/include/c++/v1/algorithm:719:71: error: invalid operands to binary expression
      ('const htr::Result' and 'const htr::Result')
    bool operator()(const _T1& __x, const _T1& __y) const {return __x < __y;}`

Having already overridden the '<' operator for the struct Result, I am not sure how to rectify the same. Looking forward to your help on resolving this. TIA.

System details 
`OS X 10.13.4 | OpenCV 3.3 | Apple LLVM version 9.1.0`

**Comment by githubharald** [comment]
I'll come back to you next week.

**Comment by githubharald** [comment]
please try to make the operator < method (DeslantImgCPU.cpp, line 17) constant: 
`bool operator < (const Result& rhs) const { return sum_alpha < rhs.sum_alpha; }`

**Comment by kalravibhor** [comment]
@githubharald : Worked like a charm. Thanks.
