### ISSUE TITLE
No package 'opencv' found

### ISSUE THREAD

**Issue by chinnuviswan** [githubharald/DeslantImg#2]
g++ --std=c++11 src/cpp/main.cpp src/cpp/DeslantImgCPU.cpp `pkg-config --cflags --libs opencv` -o DeslantImg
Package opencv was not found in the pkg-config search path.
Perhaps you should add the directory containing `opencv.pc'
to the PKG_CONFIG_PATH environment variable
No package 'opencv' found
In file included from src/cpp/main.cpp:4:0:
src/cpp/DeslantImgCPU.hpp:2:10: fatal error: opencv2/core.hpp: No such file or directory
 #include <opencv2/core.hpp>
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from src/cpp/DeslantImgCPU.cpp:1:0:
src/cpp/DeslantImgCPU.hpp:2:10: fatal error: opencv2/core.hpp: No such file or directory
 #include <opencv2/core.hpp>
          ^~~~~~~~~~~~~~~~~~
compilation terminated.

this is what i am getting although opencv is pip installed

**Comment by githubharald** [comment]
g++ is the C++ compiler and has nothing to do with Python. (also after compiling, you get a binary which you can't use with Python)
You have to install OpenCV on your system (should be installable via apt-get install).
